config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users


  resources :offers, only: %i[index show new create update edit destroy] do
    resources :bookings, only: %i[new create]
  end

  resources :bookings, only: %i[index show update edit destroy] do
    resources :reviews, only: %i[new create index]
  end
  
  resources :reviews, only: %i[destroy edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :offer
  belongs_to :user
  has_many :reviews, dependent: :destroy
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  validates :category, inclusion: { in: ["front-end", "back-end", "ux-ui"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  has_many :offers
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def offer_bookings
    offers = self.offers
    bookings = []
    offers.each do |offer|
      offer.bookings.each do |booking|
        bookings << booking
      end
    end
    return bookings
  end

  def unable_to_review?(offer)
    bookings = offer.bookings
    bookings.each do |booking|
      return booking if booking.status == "accepted" && booking.user == self && booking.reviews.blank?
    end
    return false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :params_id, only: %i[show edit update destroy]
  before_action :offer_id, only: %i[new create]
  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.offer = @offer
    if @booking.save
      redirect_to bookings_path
    else
      render 'new'
    end
  end

  def index
    @bookings = current_user.bookings
    @my_offers_bookings = current_user.offer_bookings
  end

  def show
  end

  def edit
  end

  def update
    @booking.status = params[:status]
    @booking.save
    redirect_to bookings_path
  end

  def destroy
    if (@booking.user == current_user)
      @booking.destroy
    end
    redirect_to offers_path
  end

  private

  def offer_id
    @offer = Offer.find(params[:offer_id])
  end

  def params_id
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:end_date, :begin_date)
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :offer_id, only: %i[show edit destroy update]

  def show
    @booking = Booking.new
    @bookings = @offer.bookings
    @bookings_dates = @bookings.map do |booking|
      {
        from: booking.begin_date,
        to: booking.end_date
      }
    end
    @review = Review.new
    @reviews = @offer.reviews
  end

  def index
    @offers = Offer.all
    if params[:category].present?
      @offers = Offer.where("category ilike ?", "%#{params[:category]}%")
    end

    if params[:query].present?
      sql_query = "
      offers.category ilike :query
      OR users.first_name ilike :query
      OR users.last_name ilike :query"
      @offers = Offer.joins(:user).where(sql_query, query: "%#{params[:query]}%")
    end
  end

  def new
    @offer = Offer.new
  end

  def create
    @offer = Offer.new(offer_params)

    # Found user and add it to offer.user
    @user = current_user
    @offer.user = @user

    if @offer.save!
      redirect_to offer_path(@offer.id)
    else
      render :new
    end
  end

  def edit
    if (@offer.user != current_user)
      redirect_to offers_path
    end
  end

  def update
    if (@offer.user == current_user)
      @offer.update(offer_params)
    end
    redirect_to offers_path
  end

  def destroy
    if (@offer.user == current_user)
      @offer.destroy
    end
    redirect_to offers_path
  end

  private

  def offer_id
    @offer = Offer.find(params[:id])
  end

  def offer_params
    params.require(:offer).permit(:title, :description, :price_per_day, :category)
  end
end

app/controllers/pages_controller.rb
# app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :review_id, only: %i[delete edit update]
  def new
    @review = Review.new
    @booking = Booking.find(params[:booking_id])
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @review.booking = @booking
    if @review.save!
      redirect_to offer_path(@booking.offer)
    else
      render :new
    end
  end

  def index
    @reviews = Review.all
  end

  def edit
    @review = Review.find(params[:id])
    if @review.booking.user != current_user
      redirect_to bookings_path
    end
  end

  def update
    if review.booking.user == current_user
      @review.update(review_params)
    end
    redirect_to bookings_path
  end

  def delete
    @review.destroy
    redirect_to bookings_path
  end

  private

  def review_id
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="container">
  <%= simple_form_for [ @offer, @booking ] do |f|%>
  <%= f.input :begin_date %>
  <%= f.input :end_date %>
  <%= f.submit %>
  <% end %>
</div>

app/views/bookings/index.html.erb
<div class="container d-flex justify-content-around mt-5 mb-5">

  <div class="class-applied text-center">
    <h1>Offers Apply</h1>
    <div class="card-grid-booking">
      <% @bookings.each do |booking| %>
        <div class="card-trip">
          <% if (booking.user == current_user) %>
            <%= link_to booking_path(booking.id), method: :delete, data: { confirm: "Are you sure you want to booking your offer ?"}, class: "btn btn-warning text-white booking-trash" do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
          <% end %>
          <%= link_to offer_path(booking.offer) do %>
            <%= cl_image_tag booking.offer.user.photo.key, crop: :fill, class: 'card-trip-img' %>
              <div class="card-trip-infos">
                <h2><%= booking.offer.user.last_name.capitalize + ' ' +  booking.offer.user.first_name.capitalize %></h2>
                <h3><%= booking.offer.title %></h3>
              </div>
              <div class="infos-price pt-2">
                <h2 class="card-trip-pricing"><%= booking.begin_date %></h2>
                <h2><%= booking.end_date %></h2>
              </div>
      <% end %>
              <div class="text-center mb-2">
                <% if booking.status == "accepted" %>
                  <p class="text-success">Accepted</p>
                <% elsif booking.status == "declined" %>
                  <p class="text-danger">Declined</p>
                <% elsif%>
                  <p class="text-secondary">Pending</p>
                <% end %>
              </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="class-create text-center">
    <h1>Offers Create</h1>
    <div class="card-grid-booking">
      <% @my_offers_bookings.each do |booking| %>
      <div class="card-trip">
        <% if (booking.offer.user == current_user) %>
          <%= link_to booking_path(booking.id), method: :delete, data: { confirm: "Are you sure you want to booking your offer ?"}, class: "btn btn-warning text-white booking-trash" do %>
            <i class="far fa-trash-alt"></i>
          <% end %>
        <% end %>
        <%= link_to offer_path(booking.offer) do %>
          <%= cl_image_tag booking.offer.user.photo.key, crop: :fill, class: 'card-trip-img' %>
            <div>
              <div class="card-trip-infos">
                <h2><%= booking.user.last_name.capitalize + ' ' +  booking.user.first_name.capitalize %></h2>
                <h3><%= booking.offer.title %></h3>
              </div>
        <% end %>
              <div class="infos-price pt-2">
                <h2><%= booking.offer.price_per_day %>$/day</h2>
                <h2><i class="fas fa-clock"></i>
                <%=
                  secondsInDay = 24 * 60 * 60
                  comparatedDate = (Time.now - booking.offer.created_at.localtime).to_i
                  nbrDays = comparatedDate / secondsInDay
                  nbrHours = comparatedDate / ( 60 * 60 )

                  if (comparatedDate < 86400)
                    "#{pluralize nbrHours, "hour", plural: "hours"} ago"
                  else
                    "#{pluralize nbrDays, "day", plural: "days" } ago"
                  end
                %>
                </h2>
              </div>

              <div class='footer-card text-center mb-2'>
                <% if booking.status == "pending" %>
                  <%=link_to booking_path(booking, status: "declined"), method: :patch, class:'text-danger mr-5' do %>
                    <i class="fas fa-times"></i>
                  <% end %>
                  <%=link_to booking_path(booking, status: "accepted"), method: :patch, class:'text-success ml-5' do %>
                    <i class="fas fa-check"></i>
                  <% end %>
                <% end %>
                <% if booking.status == "accepted" %>
                  <p class="text-success">Accepted</p>
                <% elsif booking.status == "declined" %>
                  <p class="text-danger">Declined</p>
                <% end %>
              </div>
            </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <%= simple_form_for [ @offer, @booking ] do |f|%>
  <%= f.input :begin_date %>
  <%= f.input :end_date %>
  <%= f.submit %>
  <% end %>
</div>

app/views/bookings/show.html.erb
<h1>A refaire</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDigitalAgency</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div id="navbarHeight" class="container-navbar"></div>
    <div class="fixed-footer">
    <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/offers/edit.html.erb
<div class="container">
  <%= simple_form_for(@offer) do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :price_per_day %>
  <%= link_to offer_path(@offer.id), class: "btn btn-success mt-2" do %>
    <i class="fas fa-undo-alt"> Back to your offer</i>
  <% end %>
  <%= f.button :submit, "Update offer", class: "btn btn-warning text-white mt-2" %>
  <% end %>
</div>

app/views/offers/index.html.erb
<div class="container mt-5 mb-5">
  <h1>OFFERS</h1>
  <div class="card-grid">
    <%= link_to new_offer_path, class: "btn btn-warning text-white create-card-btn" do %>
      <i class="fas fa-plus"></i>
    <% end %>
    <% @offers.each do |offer| %>
      <%= link_to offer_path(offer) do %>
        <div class="card-trip">
          <%= cl_image_tag offer.user.photo.key, crop: :fill, class: 'card-trip-img' %>
          <div>
            <div class="card-trip-infos">
              <h2><%= offer.user.last_name.capitalize + ' ' +  offer.user.first_name.capitalize %></h2>
              <h3>Dev <%= offer.category.capitalize %></h3>
              <h2 class="card-trip-pricing"><%= offer.price_per_day %> $ / day</h2>
              </div>
              <div class="infos-price pt-2">
                <h2 class="ml-2"><i class="far fa-calendar-alt"></i> Full Time</h2>
                <h2 class="mr-2"><i class="fas fa-clock"></i>
                  <%=
                    secondsInDay = 24 * 60 * 60
                    comparatedDate = (Time.now - offer.created_at.localtime).to_i
                    nbrDays = comparatedDate / secondsInDay
                    nbrHours = comparatedDate / ( 60 * 60 )

                    if (comparatedDate < 86400)
                      "#{pluralize nbrHours, "hour", plural: "hours"} ago"
                    else
                      "#{pluralize nbrDays, "day", plural: "days" } ago"
                    end
                  %>
                </h2>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/offers/new.html.erb
<div class="container">
  <%= simple_form_for(@offer) do |f| %>
  <%= f.input :title %>
  <%= f.input :category, collection: ["front-end", "back-end", "ux-ui"], default: 0 %>
  <%= f.input :description %>
  <%= f.input :price_per_day %>
  <%= f.submit %>
  <% end %>
</div>

app/views/offers/show.html.erb
<div class="container">
  <div class="show-container">
    <div class="title-show-container">
      <%= cl_image_tag @offer.user.photo.key, crop: :fill, class: 'avatar-big mr-5'%>
      <div class="mr-auto">
        <h2><%= @offer.user.first_name %> <%= @offer.user.last_name %></h2>
        <h2><%= @offer.title %></h2>
        <h3><%= @offer.price_per_day %> $ per day</h3>
      </div>
      <div class="d-flex flex-column align-self-start">
        <%= link_to offers_path, class: "btn btn-success mt-2" do %>
          <i class="fas fa-undo-alt"> Back to offers</i>
        <% end %>
        <% if (@offer.user == current_user) %>
          <%= link_to edit_offer_path(@offer.id), class: "btn btn-success mt-2" do %>
            <i class="fas fa-pencil-alt"> Edit my offer</i>
          <% end %>
        <% end %>
        <% if (@offer.user == current_user) %>
          <%= link_to offer_path(@offer.id), method: :delete, data: { confirm: "Are you sure you want to remove your offer ?"}, class: "btn btn-warning text-white mt-2" do %>
            <i class="far fa-trash-alt"></i>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="form-container">
      <div class="box-description">
        <h3>Description</h3>
        <p><%= @offer.description %></p>
        <h3>Langages</h3>
        <% green = '<i class="fas fa-window-minimize awesome-yellow tick ml-1"></i>' %>
        <% lightgrey = '<i class="fas fa-window-minimize awesome-lightgrey tick mr-1"></i>' %>
        <p><%= @offer.langage1 %> level : <%= green.html_safe * @offer.level1  %> <%= lightgrey.html_safe * (3 - @offer.level1)  %> </p>
        <p><%= @offer.langage2 %> level : <%= green.html_safe * @offer.level2  %> <%= lightgrey.html_safe * (3 - @offer.level2)  %> </p>
      </div>
      <div class="box-review">
        <h3>Reviews</h3>
        <% @reviews.each do |review| %>
          <div class="flex-column">
            <p><%= review.content %>
            <% case review.rating  %>
            <% when 0 %>
              <i class="ml-2 far fa-star awesome-lightgrey"></i> <i class="far fa-star awesome-lightgrey"></i> <i class="far fa-star awesome-lightgrey"></i> <i class="far fa-star awesome-lightgrey"></i> <i class="far fa-star awesome-lightgrey"></i>
            <% when 1 %>
              <i class="ml-2 fas fa-star awesome-yellow"></i> <i class="far fa-star awesome-lightgrey"></i> <i class="far fa-star awesome-lightgrey"></i> <i class="far fa-star awesome-lightgrey"></i> <i class="far fa-star awesome-lightgrey"></i>
            <% when 2 %>
              <i class="ml-2 fas fa-star awesome-yellow"></i> <i class="fas fa-star awesome-yellow"></i> <i class="far fa-star awesome-lightgrey"></i> <i class="far fa-star awesome-lightgrey"></i> <i class="far fa-star awesome-lightgrey"></i>
            <% when 3 %>
              <i class="ml-2 fas fa-star awesome-yellow"> </i> <i class="fas fa-star awesome-yellow"></i> <i class="fas fa-star awesome-yellow"></i> <i class="far fa-star awesome-lightgrey"></i> <i class="far fa-star awesome-lightgrey"></i>
            <% when 4 %>
              <i class="ml-2 fas fa-star awesome-yellow"></i> <i class="fas fa-star awesome-yellow"></i> <i class="fas fa-star awesome-yellow"></i> <i class="fas fa-star awesome-yellow"></i> <i class="far fa-star awesome-lightgrey"></i>
            <% when 5 %>
              <i class="ml-2 fas fa-star awesome-yellow"></i> <i class="fas fa-star awesome-yellow"></i> <i class="fas fa-star awesome-yellow"></i> <i class="fas fa-star awesome-yellow"></i> <i class="fas fa-star awesome-yellow"></i>
            <% end %></p>
          </div>
          <% end %>
          <% booking_review = current_user.unable_to_review?(@offer)  %>
            <%if booking_review %>

          <div>
            <h3>Let a review:</h3>
            <%= simple_form_for [ booking_review, @review] do |f| %>
            <%= f.input :content, placeholder: "Content", as: :string %>
            <%= f.input :rating, placholder: "Rating", as: :integer %>
            <%= f.submit class: "btn btn-warning text-white" %>
            <% end %>
          </div>
        <% end %>
      </div>

        <div class="box-form">
          <h3>Book <%= @offer.user.first_name %></h3>
          <%= simple_form_for [ @offer, @booking ] do |f|%>
          <%= f.input :begin_date, placeholder: "Start", as: :string,
                              required: false,
                              input_html: { id: "range_start", class: "d-none" }, label: false %>
          <%= f.input :end_date, placeholder: "End", as: :string,
                            required: false,
                            input_html: { id: "range_end", class: "d-none" }, label: false %>
          <%= f.submit class: "btn btn-warning text-white" %>
          <% end %>
          <div id="booking-form-div" data-bookings="<%= @bookings_dates.to_json %>">
        </div>
      </div>
  </div>
</div>

app/views/pages/home.html.erb
<%= render "shared/banner" %>


  <h1 class="title-HP">Concern Digital Agency :</h1>
  <div class="garniture-containe">
    <div class="row">
    <div class="col-4">
    <div class="h-card">
      <%= image_tag "find.png", class: "first-illu" %>
      <p>1-Trouvez facilement des compétences pointues
        pour vos projets et contactez gratuitement les
        profils vérifiés de votre choix. </p>
    </div>
    </div>
    <div class="col-4">
    <div class="h-card">
      <%= image_tag "work.png", class: "first-illu" %>
      <p>2-Travaillez main dans la main : décidez
        ensemble des modalités de la mission puis collaborez
        en direct. </p>
    </div>
    </div>
    <div class="col-4">
    <div class="h-card">
      <%= image_tag "programming.png", class: "first-illu" %>
      <p>3-Recommencez. La mission est terminée ? Débloquez
        le paiement en un clic et partez à la recherche de votre
        prochain talent ! </p>
    </div>
    </div>
    </div>
  </div>

  <div class="grid-homepage">

    <%= link_to offers_path do %>
    <div class="card-homepage" style=" background-color: #84a98c">
    <p>ALL</p>
    </div>
    <%end%>

    <%= link_to offers_path(category: 'front-end') do %>
    <div class="card-homepage" style=" background-color: #52796f">
    <p>FRONT-END</p>
    </div>
    <%end%>

    <%= link_to offers_path(category: 'back-end') do %>
    <div class="card-homepage" style=" background-color: #354f52">
    <p>BACK-END</p>
    </div>
    <%end%>

    <%= link_to offers_path(category: 'ux-ui') do %>
    <div class="card-homepage" style=" background-color: #2f3e46">
    <p>UI/UX</p>
    </div>
    <%end%>

  </div>

  <% if user_signed_in?  %>
    <div class="contain-littlebanner d-none">
      <%= link_to "Sign up", new_user_registration_path, class: "btn btn-littlebanner"  %>
    </div>
  <% else  %>
    <div class="contain-littlebanner">
      <%= link_to "Sign up", new_user_registration_path, class: "btn btn-littlebanner"  %>
    </div>
  <% end %>

</div>


<script>
  document.getElementById("navbarHeight").classList.remove("container-navbar");
</script>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url(https://images.unsplash.com/photo-1487446929682-f62f73984006?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1351&q=80);">
  <div class="text-banner">
    <h1>DIGITAL AGENCY</h1>
    <p>Platform for freelancers</p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="icons">
  <%= link_to "#", class: "icon" do  %>
  <i class="fab fa-facebook-square"></i>
  <% end %>

  <%= link_to "#", class: "icon"  do  %>
  <i class="fab fa-github-square"></i>
  <% end %>

  <%= link_to "#", class: "icon"  do  %>
  <i class="fab fa-instagram-square"></i>
  <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo2.png", class: "logonavbar" %>
    <% end %>
    <%= render 'shared/searchbar' %>
    <div class="link">
      <% if user_signed_in? %>
      <div class="list-contain">
        <%= cl_image_tag current_user.photo.key, crop: :fill, class: 'avatar'%>
        <div class="dropdownmenu d-none">
          <%= link_to "Personal space", bookings_path, class: "dropdownitem" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdownitem" %>
        </div>
      </div>
      <% else %>
      <%= link_to "Login", new_user_session_path, class: "btn-navbar" %>
      <%= link_to "Sign up", new_user_registration_path, class: "btn-navbar2" %>
      <% end %>
    </div>
</div>

app/views/shared/_searchbar.html.erb
<div class="searchbar-contain">
  <%= form_tag(offers_path, method: 'get') do %>
        <%= text_field_tag :query, params[:query], class: "searchbar", placeholder: "Search category" %>
        <%= button_tag(type: "submit", class: "btn-searchbar") do  %>
          <i class="fas fa-search"></i>
        <% end %>
  <% end %>
</div>